### ISSUE TITLE
View or edit?

### ISSUE THREAD

**Issue by buddhaCode** [discoverydesign/filament-gaze#5]
The default message states:

> This page is currently being viewed by Test User.

I think it would be more clear for the user to tell, that this page is currently edited and not just viewed?! The main purpose of the edit page is to edit a resource not to view it. What do you think about it?

> This page is currently being **edited** by Test User.

Best,
Arne

**Comment by 0wain** [comment]
Hey,

We can't directly change the work "viewed" to "edited" because it also lists people who are also viewing the page but don't have control. But it does say underneath the person who has "control", which would be the current editor.

The package supports translations, so you could in theory publish these translations and edit them if you had a specific way of phrasing things.

**Comment by buddhaCode** [comment]
Oh sure. That makes sense. I didn't take into account, that there could be more than 2 users on the same site. dooooh.
